[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]

[bootstrap.packages]
"brew:jq" = "1.8.2"
"brew:stow" = "latest"
"pacman:btop" = "latest"
"pacman:jq" = "1.8.2"
"pacman:stow" = "latest"

[tools]
bat = "0.26.1"
fzf = "0.73.1"
go = "1.26"
herdr = "0.7.1"
jj = "0.40.0"
rg = "15.1.0"
starship = "1.26.0"
